#!/bin/bash

#Variabelen
server="";
passw="";
omg="";
dirOnServer="";

#laad de inputparameter filename in:

if [ $1 == "-h" ]; then
	echo "example: $0 [directory] [number]";
	echo "creates n-number of copies of all files in the directory."
	echo "";
	exit;
fi

if [ -d $1 ]; then
	dir=$1;
else
	echo "The first parameter must be an directory...";	
fi


if [ $2 -gt 0 ]; then 
	amount="$2";
else
	echo "";
	echo "second argument must be a number bigger than 0...";
fi


#genereer een reeks van bestandsnamen
mkdir ./temp

for unieke_id in $(seq 1 $amount); do
	for FILE in $dir/*; do
		filename=${FILE##*/};
		basename=${filename%%.*};
		suffix=${filename#*.};
		cp  "$dir/$filename" "./temp/${basename}${unieke_id}.${suffix}";
	done
done

#lftp -e "mput -O ./$dirOnServer ./temp/*; bye" -u $omg,$passw $server

#rm -r ./temp;

echo "script terminated successfully...";
exit;
